version: '3'

services:
  mysql:
    image: mysql:5.7.20
    volumes:
      - mysql-data:/var/lib/mysql
    expose:
      - 3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql

  web:
    build:
      context: .
      dockerfile: config/docker/web/prod/Dockerfile
    depends_on:
      - mysql
    labels:
      - "com.spotistats.web"

  nginx:
    build:
      context: ./config/docker/nginx/
    depends_on:
      - web

volumes:
  mysql-data: